name = "rgf/expbuild"
version = "0.2.6"
description = "luau bundler for executor scripts with support for macros"
authors = ["SDOT"]
license = "MPL 2.0"
includes = [
	"*.luau",
	"LICENSE",
	"README.md",
	"pesde.toml",
	".luaurc",
	"example.expbuild.toml",
]
repository = "https://github.com/RGFQQ/ExpBuild"

[target]
environment = "lune"

[target.scripts]
expbuild = "bin.luau"

[indices]
default = "https://github.com/RGFQQ/pesde-index"
pesde = "https://github.com/pesde-pkg/index"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.2", index = "pesde" }
unzip = { name = "0x5eal/unzip", version = "^0.1.1", target = "luau", index = "pesde" }
argparse = { name = "caveful_games/argparse", version = "^0.1.2", index = "pesde" }

[dev_dependencies]
stylua = { name = "pesde/stylua", version = "^2.0.2", index = "pesde" }

[engines]
pesde = "^0.6.0"
lune = "^0.8.9"
